const API_TIMEOUT_MS = 25000;

const NETWORK_ERROR_CODES = new Set([
  'ECONNREFUSED',
  'ETIMEDOUT',
  'ECONNRESET',
  'EHOSTUNREACH',
  'ENOTFOUND',
  'EAI_AGAIN',
  'ERR_NETWORK',
  'ERR_SOCKET_CONNECTION_TIMEOUT',
  'ERR_CONNECTION_REFUSED',
  'ERR_HTTP_REQUEST_TIMEOUT',
  'ABORT_ERR',
]);

const API_RETRY_MAX_ATTEMPTS = 4;
const API_RETRY_BASE_MS = 1000;
const API_RETRY_MAX_MS = 32000;
const API_RETRY_JITTER_RATIO = 0.25;

module.exports = {
  API_TIMEOUT_MS,
  NETWORK_ERROR_CODES,
  API_RETRY_MAX_ATTEMPTS,
  API_RETRY_BASE_MS,
  API_RETRY_MAX_MS,
  API_RETRY_JITTER_RATIO,
};
